/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import static java.lang.System.out;
import java_cup.parser;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.Symbol;
import java_cup.internal_error;
import jflex.exceptions.SilentExit;
import static jflex.logging.Out.println;
import jflex.logging.Out;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
 
import jflex.Main;


public class App {

    public static void GenerarLexerParser()throws SilentExit, Exception{
        String basePath, fullPathLexer, fullPathparser, jlexer, jparser, jlexerCarpeta;
        MainFlexCup mfjc;
        
        basePath = System.getProperty("user.dir");
        System.out.println(basePath);
        mfjc = new MainFlexCup();
        
        //genera el analizador léxico y sintáctico
        
        fullPathLexer = basePath+"\\app\\src\\Adicionales\\BasicLexerCup.jflex";
        fullPathparser = basePath+"\\app\\src\\Adicionales\\BasicParser.cup";

        //.java de parser y lexer
        jparser = "parser.java";
        jlexer = "BasicLexerCup.java";
        jlexerCarpeta = "Adicionales";
        //elimina archivos
        Files.deleteIfExists(Paths.get(basePath+"\\app\\src\\main\\java\\ParserLexer\\sym.java"));
        Files.deleteIfExists(Paths.get(basePath+"\\app\\src\\main\\java\\ParserLexer\\"+jparser));
        Files.deleteIfExists(Paths.get(basePath+"\\app\\src\\main\\java\\ParserLexer\\"+jlexer));
        
        mfjc.iniLexerParser(fullPathLexer, fullPathparser);
        //mover archivos
        Files.move (Paths.get(basePath+"\\sym.java"), Paths.get(basePath+"\\app\\src\\main\\java\\org\\example\\ParserLexer\\sym.java"));
        Files.move (Paths.get(basePath+"\\"+jparser), Paths.get(basePath+"\\app\\src\\main\\java\\org\\example\\ParserLexer\\"+jparser));
        Files.move (Paths.get(basePath+"\\app\\src\\"+jlexerCarpeta+"\\"+jlexer), Paths.get(basePath+"\\app\\src\\main\\java\\org\\example\\ParserLexer\\"+jlexer));
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        GenerarLexerParser();
    }
}
